# Generated by Django 3.2.7 on 2021-09-19 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=128)),
                ('cost_per_minute', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
